CREATE TABLE USERS(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NICKNAME VARCHAR(70) NOT NULL UNIQUE,
    PASSWORD VARCHAR(70) NOT NULL,
    NAME VARCHAR(70) NOT NULL,
    ISADMIN BIT DEFAULT NULL,
    BASKET VARCHAR(255)
);
CREATE TABLE PRODUCTS(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    IMAGE BLOB,
    PRICE INT NOT NULL
);
CREATE TABLE ORDERS(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUCTS VARCHAR(200) NOT NULL,
    CUSTOMERID INT,
    CREATEDAT DATE,
    ISPAID BIT,
    FOREIGN KEY (CUSTOMERID) REFERENCES Users(ID)
);
CREATE TABLE BLACKLIST(
    ID INTEGER,
    NICKNAME VARCHAR(70),
    PASSWORD VARCHAR(70),
    NAME VARCHAR(70),
    ISADMIN BOOLEAN,
    BASKET VARCHAR(255)
);

